### ISSUE TITLE
Add type field on labels

### ISSUE THREAD

**Issue by 0xsign** [llamafolio/llamafolio-labels#2]
See https://github.com/llamafolio/llamafolio-app/issues/326#issuecomment-1273284977

Add a field on labels to help cluster them in categories. The frontend can change the tag color based on this type

**Comment by eabz** [comment]
I can take this and write documentation about proper ways to add the labels.

**Comment by 0xsign** [comment]
That would be awesome, maybe a table of what each type means in the Readme ?

Maybe export a union type definition in the index too ?

**Comment by 0xsign** [comment]
Closed by https://github.com/llamafolio/llamafolio-labels/pull/3
